export const categories = [
  {
    id: 1,
    name: 'Electronics & Computers',
    slug: 'electronics',
    icon: '/icons/electronics.gif',
    content: 'Electronics and Computers...',
  },
  {
    id: 2,
    name: 'Home & Kitchenware',
    slug: 'home-and-kitchenware',
    icon: '/icons/homeware.gif',
    content: 'Home and Kitchenware...',
  },
  {
    id: 3,
    name: 'Advanced Digital Courses',
    slug: 'digital-courses',
    icon: '/icons/courses.gif',
    content: 'Digital Courses...',
  },
  {
    id: 4,
    name: "Babies' & Kids' Toys",
    slug: 'kids',
    icon: '/icons/kids.gif',
    content: 'Kids...',
  },
  {
    id: 5,
    name: 'Phones & Tablets',
    slug: 'phones-and-tablets',
    icon: '/icons/phones.gif',
    content: 'Phones and Tabs...',
  },
  {
    id: 6,
    name: 'Computers & Accessories',
    slug: 'computers-and-accessories',
    icon: '/icons/computers.gif',
    content: 'Computers and Accessories...',
  },
  {
    id: 7,
    name: 'Automobile & Motorcycles',
    slug: 'automobile-and-motorcycles',
    icon: '/icons/automobile.gif',
    content: 'Automobile and Motorcycles...',
  },
  {
    id: 8,
    name: 'Groceries & Foodstuff',
    slug: 'groceries',
    icon: '/icons/groceries.gif',
    content: 'Groceries and Foodstuff...',
  },
  {
    id: 9,
    name: 'Gaming & Accessories',
    slug: 'gaming',
    icon: '/icons/gaming.gif',
    content: 'Gamig and Accessories...',
  },
  {
    id: 10,
    name: 'Fashion & Wears',
    slug: 'fashion',
    icon: '/icons/fashion.gif',
    content: 'Fashion and Wears...',
  },
]

export const navLinks = [
  { name: 'Home', link: '/' },
  { name: 'Flash Sale', link: '/flash-sale' },
  { name: 'Coupons', link: '/coupons' },
  { name: 'All Brands', link: '/brands' },
  { name: 'All Categories', link: '/categories' },
  { name: 'All Sellers', link: '/sellers' },
]
